# syntax=docker/dockerfile:1

ARG BASE_IMAGE=registry.access.redhat.com/ubi8/ubi-minimal:8.10-1756195339
ARG JS_IMAGE=registry.access.redhat.com/ubi8/nodejs-20-minimal:1-78
ARG JS_PLATFORM=linux/amd64
ARG GO_IMAGE=golang:1.22.7-bullseye

ARG GO_SRC=go-builder
ARG JS_SRC=js-builder

FROM --platform=${JS_PLATFORM} ${JS_IMAGE} as js-builder

ENV NODE_OPTIONS=--max_old_space_size=8000

USER root
WORKDIR /tmp/grafana

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn
COPY packages packages
COPY plugins-bundled plugins-bundled
COPY public public

RUN npm install -g yarn@1.22.11
RUN yarn install --immutable

COPY tsconfig.json .eslintrc .editorconfig .browserslistrc .prettierrc.js babel.config.json ./
COPY public public
COPY scripts scripts
COPY emails emails

ENV NODE_ENV production
RUN yarn build

COPY public/build/static/source_*.tar.gz public/build/static/

FROM ${GO_IMAGE} as go-builder

ARG COMMIT_SHA=""
ARG BUILD_BRANCH=""
ARG GO_BUILD_TAGS="oss"
ARG WIRE_TAGS="oss"
ARG BINGO="true"

USER root
WORKDIR /tmp/grafana

COPY go.* ./
COPY .bingo .bingo

# Include vendored dependencies
COPY pkg/util/xorm/go.* pkg/util/xorm/
COPY pkg/build/go.* pkg/build/

RUN go mod download
RUN if [[ "$BINGO" = "true" ]]; then \
  go install github.com/bwplotka/bingo@latest && \
  bingo get -v; \
  fi

COPY embed.go Makefile build.go package.json ./
COPY cue.mod cue.mod
COPY kinds kinds
COPY local local
COPY packages/grafana-schema packages/grafana-schema
COPY public/app/plugins public/app/plugins
COPY public/api-merged.json public/api-merged.json
COPY pkg pkg
COPY scripts scripts
COPY conf conf
COPY .github .github
COPY LICENSE ./

ENV COMMIT_SHA=${COMMIT_SHA}
ENV BUILD_BRANCH=${BUILD_BRANCH}

RUN apt-get update && apt-get install -y gcc g++ make git
RUN make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}

# helpers for COPY --from
FROM ${GO_SRC} as go-src
FROM ${JS_SRC} as js-src

# Final stage
FROM ${BASE_IMAGE}

LABEL maintainer="Grafana team <hello@grafana.com>"

ARG GF_UID="472"
ARG GF_GID="0"

ENV PATH="/usr/share/grafana/bin:$PATH" \
  GF_PATHS_CONFIG="/etc/grafana/grafana.ini" \
  GF_PATHS_DATA="/var/lib/grafana" \
  GF_PATHS_HOME="/usr/share/grafana" \
  GF_PATHS_LOGS="/var/log/grafana" \
  GF_PATHS_PLUGINS="/usr/share/grafana/plugins" \
  GF_PATHS_PROVISIONING="/etc/grafana/provisioning"

WORKDIR $GF_PATHS_HOME
USER root

RUN microdnf upgrade --refresh -y && microdnf install shadow-utils
RUN microdnf install shadow-utils
RUN microdnf install wget
RUN microdnf install tar
RUN microdnf install gzip
RUN microdnf install unzip

# setup plugins dir
RUN mkdir -p plugins/

# pulse telemetry api plugin
RUN mkdir -p plugins/pulse-telemapi-plugin/
RUN wget https://github.com/goldmansachs/pulse-telemapi-plugin/releases/download/v1.1.0/build.zip
RUN unzip build.zip
RUN mv -f build/dist/* plugins/pulse-telemapi-plugin/ && rm -r /usr/share/grafana/build.zip && rm -r /usr/share/grafana/build

# sysdig plugin
RUN mkdir -p plugins/sysdig/
RUN wget "https://download.sysdig.com/stable/grafana-sysdig-datasource/grafana-sysdig-datasource-v0.8.tgz"
RUN tar -xvf grafana-sysdig-datasource-v0.8.tgz
RUN mv -f sysdig/* plugins/sysdig && rm -r /usr/share/grafana/grafana-sysdig-datasource-v0.8.tgz && rm -r /usr/share/grafana/sysdig

# bigquery plugin
RUN mkdir -p plugins/bigquery/
RUN wget https://github.com/goldmansachs/bigquery-grafana-plugin/releases/download/gs_v2.0.2/build.zip
RUN unzip build.zip
RUN mv -f build/dist/* plugins/bigquery/ && rm -r /usr/share/grafana/build.zip && rm -r /usr/share/grafana/build

# json plugin
RUN mkdir -p plugins/marcusolsson-json-datasource
RUN wget "https://github.com/grafana/grafana-json-datasource/releases/download/v1.3.14/marcusolsson-json-datasource-1.3.14.zip"
RUN unzip marcusolsson-json-datasource-1.3.14.zip
RUN mv -f marcusolsson-json-datasource/* plugins/marcusolsson-json-datasource && rm -r /usr/share/grafana/marcusolsson-json-datasource-1.3.14.zip && rm -r /usr/share/grafana/marcusolsson-json-datasource

# treemap plugin
RUN mkdir -p plugins/marcusolsson-treemap-panel
RUN wget "https://github.com/grafana/grafana-treemap-panel/releases/download/v2.0.1/marcusolsson-treemap-panel-2.0.1.zip"
RUN unzip marcusolsson-treemap-panel-2.0.1.zip
RUN mv -f marcusolsson-treemap-panel/* plugins/marcusolsson-treemap-panel && rm -r /usr/share/grafana/marcusolsson-treemap-panel-2.0.1.zip && rm -r /usr/share/grafana/marcusolsson-treemap-panel

# opensearch plugin
RUN mkdir -p plugins/grafana-opensearch-plugin
RUN wget "https://github.com/grafana/opensearch-datasource/releases/download/v2.16.1/grafana-opensearch-datasource-2.16.1.zip"
RUN unzip grafana-opensearch-datasource-2.16.1.zip -d plugins/grafana-opensearch-plugin
RUN rm -r /usr/share/grafana/grafana-opensearch-datasource-2.16.1.zip

COPY conf ./conf

RUN export GF_GID_NAME=$(getent group $GF_GID | cut -d':' -f1) && \
  mkdir -p "$GF_PATHS_HOME/.aws" && \
  useradd --system -u $GF_UID -G "$GF_GID_NAME" grafana && \
  mkdir -p "$GF_PATHS_PROVISIONING/datasources" \
  "$GF_PATHS_PROVISIONING/dashboards" \
  "$GF_PATHS_PROVISIONING/notifiers" \
  "$GF_PATHS_PROVISIONING/plugins" \
  "$GF_PATHS_PROVISIONING/access-control" \
  "$GF_PATHS_PROVISIONING/alerting" \
  "$GF_PATHS_LOGS" \
  "$GF_PATHS_PLUGINS" \
  "$GF_PATHS_DATA" && \
  cp conf/sample.ini "$GF_PATHS_CONFIG" && \
  cp conf/ldap.toml /etc/grafana/ldap.toml && \
  chown -R "grafana:$GF_GID_NAME" "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING" && \
  chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"

COPY --from=go-src /tmp/grafana/bin/grafana* /tmp/grafana/bin/*/grafana* ./bin/
COPY --from=js-src /tmp/grafana/public ./public
COPY --from=go-src /tmp/grafana/LICENSE ./

# Additional plugins
RUN mkdir -p plugins
RUN grafana cli --pluginsDir ./plugins --pluginUrl https://download.sysdig.com/stable/grafana-sysdig-datasource/grafana-sysdig-datasource-v0.11.zip plugins install grafana-sysdig-datasource
RUN grafana cli --pluginsDir ./plugins --pluginUrl https://github.com/goldmansachs/bigquery-grafana-plugin/releases/download/gs_v1.9.5/grafana-bigquery-datasource-1.9.2.zip plugins install grafana-bigquery-datasource
RUN grafana cli --pluginsDir ./plugins plugins install michaeldmoore-multistat-panel
RUN grafana cli --pluginsDir ./plugins plugins install marcusolsson-dynamictext-panel

USER grafana
RUN grafana cli plugins install neocat-cal-heatmap-panel 0.0.4

EXPOSE 3000

ARG RUN_SH=./packaging/docker/run.sh

COPY ${RUN_SH} /run.sh

USER grafana
ENTRYPOINT [ "/run.sh" ]
